services:
  mediasort:
    build:
      context: .
      dockerfile: Dockerfile
    user: "${UID}:${GID}"
    volumes:
      - ${INPUT_PATH}:/app/input
      - ${OUTPUT_PATH}:/app/output
      - data:/app/data

    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    working_dir: /app
    command: sh -c "umask 007 && python main.py"

volumes:
  data: